# remap prefix
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# vim-style move between panes
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

# Swap pane
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# Enable mouse control (clickable windows, panes, resizeable panes)
set -g mouse on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Move window up/down in list
bind Up swap-window -t -1 \; select-window -t -1
bind Down swap-window -t +1 \; select-window -t +1

# Stop rename windows automatically
set -g allow-rename off
